quartz( width = 5, height= 4)
> quartz(, 5, 5)
> layout(matrix(c(1,2,3,3), nrow = 2, byrow = TRUE))
> plot(Girth, Height)
> par(mar = c(3, 3, 1, 1), mgp = c(1.6, 0.2, 0), tcl = 0.2)
> plot(Girth, Height)
> par(mar= c(3, 3, 2, 1), mgp = c(1.6, 0.2, 0), tcl = 0.2)
> plot(Girth, Height, axes = FALSE, xlim = c(8, 22))
> axis(1, tcl = -0.3)
> axis(2, tick = F)
> rug(Height, side = 2, col= 2)
> title("A Thrid, Very Wide, Plot")